---
# This role contains tasks for configuring and starting ucarp service

- name: download and install ucarp service (Redhat)
  yum: name=ucarp state=present
  when: ansible_os_family == "RedHat"

- name: download and install ucarp service (Ubuntu)
  apt: name=ucarp state=present
  when: ansible_os_family == "Debian"

- name: copy the ucarp start/stop script
  template: src=ucarp.sh.j2 dest=/usr/bin/ucarp.sh mode=u=rwx,g=rx,o=rx

- name: copy the vip up and down scripts used by ucarp
  copy: src=ucarp/ dest=/usr/bin/ucarp/ mode=u=rwx,g=rx,o=rx

- name: copy systemd units for ucarp
  copy: src=ucarp.service dest=/etc/systemd/system/ucarp.service

- name: start ucarp
  service: name=ucarp state=started
