---
# You can override vars by using host or group vars

###########
# GENERAL #
###########

fetch_directory: fetch/

cephx: true


##########
# DOCKER #
##########

mds_containerized_deployment: false
ceph_mds_docker_username: ceph
ceph_mds_docker_imagename: daemon
ceph_mds_docker_extra_env: "MDS_NAME={{ ansible_hostname }}" # comma separated variables
