FROM docker

ADD systemtests/testdata/ceph/policy1.json /policy.json
ADD systemtests/testdata/globals/global1.json /global.json
ADD build/scripts/autorun-bootstrap.sh /bootstrap.sh
RUN chmod +x /bootstrap.sh
ENTRYPOINT [ "/bin/sh", "/bootstrap.sh"  ]
