---
- include: pre_requisite.yml
  when: not restapi_containerized_deployment

- include: start_restapi.yml
  when: not restapi_containerized_deployment

- include: ./docker/main.yml
  when: restapi_containerized_deployment
