---
- name: check if ceph rest api is already started
  shell: "pgrep ceph-rest-api"
  changed_when: false
  failed_when: false
  register: restapi_status

- name: start ceph rest api
  shell: "nohup ceph-rest-api &"
  changed_when: false
  when: restapi_status.rc != 0
