---
# This play contains tasks for cleaning up etcd

- name: stop etcd
  service: name=etcd state=stopped

- name: cleanup iptables for etcd
  shell: iptables -D INPUT -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "{{ etcd_rule_comment }} ({{ item }})"
  become: true
  with_items:
    - "{{ etcd_client_port1 }}"
    - "{{ etcd_client_port2 }}"
    - "{{ etcd_peer_port1 }}"
    - "{{ etcd_peer_port2 }}"
