---
# This role contains tasks for installing ansible

- name: install ansible (redhat)
  yum:
    name: ansible
    enablerepo: epel-testing
    state: latest
  when: ansible_os_family == "RedHat"

- name: add ansible apt repository (debian)
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
    validate_certs: "{{ validate_certs }}"
  when: ansible_os_family == "Debian"

- name: install ansible (debian)
  apt: name=ansible state=latest
  when: ansible_os_family == "Debian"
