#!/bin/bash
#
# volmaster - start the Contiv Storage master service
#
# chkconfig: - 91 91
#
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6

## Edit this parameter! Volplugin will not work across hosts if you don't.
PREFIX=/volplugin
LISTEN=":9005"
ETCD="http://localhost:2379"

case "$1" in
  start)
    nohup bash -c "/usr/sbin/volmaster --etcd=${ETCD} --listen=${LISTEN} --prefix=${PREFIX} &>/var/log/volplugin.log &"
  ;;
  stop)
    pkill volmaster 
  ;;
  restart)
    $0 stop
    $0 start
  ;;
esac
