#!/bin/bash
#
# volplugin - start the Contiv Storage plugin service
#
# chkconfig: - 91 91
#
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6

## Edit this parameter! Volplugin will not work across hosts if you don't.
MASTER_HOSTNAME=localhost:9005

case "$1" in
  start)
    nohup bash -c "/usr/sbin/volplugin --master=${MASTER_HOSTNAME} &>/var/log/volplugin.log &"
  ;;
  stop)
    pkill volplugin
  ;;
  restart)
    $0 stop
    $0 start
  ;;
esac
