- name: install/upgrade base packages (redhat)
  yum:
    name: "{{ item }}"
    update_cache: true
    state: latest
  with_items:
    - vim
    - git
    - mercurial
    - gcc
    - perl
    - time
    - tcpdump
