---
# This play contains tasks for cleaning up contiv_network services

- name: stop netmaster
  service: name=netmaster state=stopped

- name: stop aci-gw container
  service: name=aci-gw state=stopped

- name: stop netplugin
  service: name=netplugin state=stopped

- name: cleanup netmaster host alias
  lineinfile:
    dest: /etc/hosts
    regexp: " netmaster$"
    state: absent
  become: true

- name: cleanup iptables for contiv network control plane
  shell: iptables -D INPUT -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "{{ netplugin_rule_comment }} ({{ item }})"
  become: true
  with_items:
    - "{{ ofnet_master_port }}"
    - "{{ ofnet_agent_port1 }}"
    - "{{ ofnet_agent_port2 }}"
    - "{{ netmaster_port }}"
    - "{{ gobgp_grpc_port }}"
    - "{{ bgp_port }}"

- include: ovs_cleanup.yml
