---

- name: pvcreate check for {{ docker_device }}
  shell: "pvdisplay {{ docker_device }}"
  register: pvcreated
  ignore_errors: true

- name: pvcreate {{ docker_device }}
  shell: "pvcreate {{ docker_device }}"
  when: pvcreated|failed

- name: vgcreate check for {{ docker_device }}
  shell: "vgdisplay contiv"
  register: vgcreated
  ignore_errors: true

- name: vgcreate contiv
  shell: "vgcreate contiv {{ docker_device }}"
  when: vgcreated|failed

- name: lvcreate check for {{ docker_device }}
  shell: "lvdisplay contiv | grep -q dockerthin"
  register: lvcreated
  ignore_errors: true

- name: lvcreate contiv-dockerthin
  shell: lvcreate -n dockerthin -T contiv --size {{ docker_device_size }}
  when: lvcreated|failed
  register: thin_provisioned
