---
- name: run the ceph rest api docker image
  docker:
    image: "{{ ceph_restapi_docker_username }}/{{ ceph_restapi_docker_imagename }}"
    name: "{{ ansible_hostname }}-ceph-restapi"
    net: host
    expose: "{{ ceph_restapi_port }}"
    state: running
    env: "RESTAPI_IP={{ hostvars[inventory_hostname]['ansible_' + ceph_restapi_docker_interface]['ipv4']['address'] }},CEPH_DAEMON=RESTAPI,{{ ceph_restapi_docker_extra_env }}"
    volumes: "/etc/ceph:/etc/ceph"
